### ISSUE TITLE
Add distributed clock

### ISSUE THREAD

**Issue by CendreQuasar540** [jimy-byerley/etherage#7]
Add method/class to enforce clock synchronization between master and slave during initialization process.

**Comment by jimy-byerley** [comment]
The clock implementation is now precise at ~50µs
- this is huge according to the ETG specifications, so improvements should be made
- yet this is better than nothing

We will try to merge it in the master branch, and see what to improve afterward

improvements to investigate:
- [ ] better control of the ethercat frame sending (currently flushing a bufferized send, but it does not guarantee all PDUs will be in the same frame)
- [ ] realtime kernel patch
- [ ] different ethernet adapters
- [ ] measure the time regularity of `tokio`

**Comment by jimy-byerley** [comment]
Some of our problems are coming from the tokio timers `tokio::time::Interval`, according to [this issue](https://github.com/tokio-rs/tokio/issues/5021), their implementation is not precise below 1ms, and we need 1µs
Let's use [`tokio-timerfd`](https://docs.rs/tokio-timerfd/latest/tokio_timerfd/struct.Interval.html) instead, experimentation shows that it is precise at least at 10µs

before: 
![image](https://github.com/jimy-byerley/etherage/assets/7940753/0a70d26c-8e48-43e0-86af-f5957e7183ee)

after:  
![image](https://github.com/jimy-byerley/etherage/assets/7940753/98713a4c-2317-4431-88da-6f888a3f3e6e)
